package PaginaPrincipal;

import AccionEspecial.AccionBotones;
import java.awt.Color;

public class PaginaPrincipal extends javax.swing.JFrame {

    AccionBotones accionBotones = new AccionBotones();

    public PaginaPrincipal() {

        initComponents();

        this.setTitle("Pagina Principal");
        this.setExtendedState(6);
        this.getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaInicio = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cambiarPanelMenu = new javax.swing.JPanel();
        bComprobante = new rojeru_san.rsbutton.RSButtonEffect();
        bProducto = new rojeru_san.rsbutton.RSButtonEffect();
        bCategoria = new rojeru_san.rsbutton.RSButtonEffect();
        bReporte = new rojeru_san.rsbutton.RSButtonEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cajaInicio.setBackground(new java.awt.Color(221, 87, 76));

        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        bsalir.setContentAreaFilled(false);
        bsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KEFISH KOREA - ECUADOR");

        javax.swing.GroupLayout cajaInicioLayout = new javax.swing.GroupLayout(cajaInicio);
        cajaInicio.setLayout(cajaInicioLayout);
        cajaInicioLayout.setHorizontalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaInicioLayout.setVerticalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(cajaInicio);
        cajaInicio.setBounds(0, 0, 1370, 63);

        PanelCambio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LogoFondo.jpg"))); // NOI18N
        jLabel2.setText("s");

        javax.swing.GroupLayout PanelCambioLayout = new javax.swing.GroupLayout(PanelCambio);
        PanelCambio.setLayout(PanelCambioLayout);
        PanelCambioLayout.setHorizontalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGroup(PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCambioLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(PanelCambioLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        PanelCambioLayout.setVerticalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCambio);
        PanelCambio.setBounds(320, 70, 1173, 635);

        cambiarPanelMenu.setBackground(new java.awt.Color(204, 204, 204));

        bComprobante.setBackground(new java.awt.Color(187, 186, 186));
        bComprobante.setForeground(new java.awt.Color(51, 51, 51));
        bComprobante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoMatricula.png"))); // NOI18N
        bComprobante.setText("      Inicio/Venta");
        bComprobante.setAlignmentY(0.0F);
        bComprobante.setColorHover(new java.awt.Color(171, 170, 170));
        bComprobante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobanteActionPerformed(evt);
            }
        });

        bProducto.setBackground(new java.awt.Color(187, 186, 186));
        bProducto.setForeground(new java.awt.Color(51, 51, 51));
        bProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono producto.png"))); // NOI18N
        bProducto.setText("      Productos");
        bProducto.setAlignmentY(0.0F);
        bProducto.setColorHover(new java.awt.Color(171, 170, 170));
        bProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoActionPerformed(evt);
            }
        });

        bCategoria.setBackground(new java.awt.Color(187, 186, 186));
        bCategoria.setForeground(new java.awt.Color(51, 51, 51));
        bCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono categoria.png"))); // NOI18N
        bCategoria.setText("      Categoria");
        bCategoria.setAlignmentY(0.0F);
        bCategoria.setColorHover(new java.awt.Color(171, 170, 170));
        bCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriaActionPerformed(evt);
            }
        });

        bReporte.setBackground(new java.awt.Color(187, 186, 186));
        bReporte.setForeground(new java.awt.Color(51, 51, 51));
        bReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoReporte.png"))); // NOI18N
        bReporte.setText("      Reporte de Venta");
        bReporte.setAlignmentY(0.0F);
        bReporte.setColorHover(new java.awt.Color(171, 170, 170));
        bReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarPanelMenuLayout = new javax.swing.GroupLayout(cambiarPanelMenu);
        cambiarPanelMenu.setLayout(cambiarPanelMenuLayout);
        cambiarPanelMenuLayout.setHorizontalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        cambiarPanelMenuLayout.setVerticalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        getContentPane().add(cambiarPanelMenu);
        cambiarPanelMenu.setBounds(10, 70, 290, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bsalirActionPerformed


    private void bComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobanteActionPerformed
        accionBotones.botonVenta(PanelCambio);
    }//GEN-LAST:event_bComprobanteActionPerformed

    private void bProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoActionPerformed
        accionBotones.botonProducto(PanelCambio);
    }//GEN-LAST:event_bProductoActionPerformed

    private void bCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriaActionPerformed
        accionBotones.botonCategoria(PanelCambio);
    }//GEN-LAST:event_bCategoriaActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
        accionBotones.botonReporte(PanelCambio);
    }//GEN-LAST:event_bReporteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelCambio;
    private rojeru_san.rsbutton.RSButtonEffect bCategoria;
    private rojeru_san.rsbutton.RSButtonEffect bComprobante;
    private rojeru_san.rsbutton.RSButtonEffect bProducto;
    private rojeru_san.rsbutton.RSButtonEffect bReporte;
    private javax.swing.JButton bsalir;
    private javax.swing.JPanel cajaInicio;
    private javax.swing.JPanel cambiarPanelMenu;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
